services:
  solana-tracker:
    build: .
    ports:
      - "8000:8000"
    #environment:
    #  - CACHE_TTL_SECONDS=60
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    depends_on:
      - solana-tracker
      #- alertmanager

  #alertmanager:
  #  image: prom/alertmanager:latest
  #  ports:
  #    - "9093:9093"
  #  volumes:
  #    - ./alertmanager:/etc/alertmanager
  #  command:
  #    - '--config.file=/etc/alertmanager/config.yml'
  #    - '--storage.path=/alertmanager'
  #  restart: unless-stopped
  #  networks:
  #    - monitoring

  #grafana:
  #  image: grafana/grafana:latest
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - grafana_data:/var/lib/grafana
  #  environment:
  #    - GF_SECURITY_ADMIN_PASSWORD=admin
  #  restart: unless-stopped
  #  networks:
  #    - monitoring
  #  depends_on:
  #    - prometheus

volumes:
  prometheus_data:
  grafana_data:

